
version: '3'
services:
  postgres:
    image: postgres:11
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - 'postgres_data2:/var/lib/postgresql/data'

  keycloak:
    image: quay.io/keycloak/keycloak:17.0.0
    environment:
      - KEYCLOAK_ADMIN=${KEYCLOAK_USER}
      - KEYCLOAK_ADMIN_PASSWORD=${KEYCLOAK_PASSWORD}
      - PROXY_ADDRESS_FORWARDING=true
      - KC_HTTP_ENABLED=true
      - KC_PROXY=passthrough
      - KC_DB=postgres
      - KC_DB_URL=jdbc:postgresql://postgres/${POSTGRES_DB}
      - KC_DB_USERNAME=${POSTGRES_USER}
      - KC_DB_PASSWORD=${POSTGRES_PASSWORD}
      - KC_SPI_THEME_DEFAULT=steedos
      - KC_HOSTNAME_STRICT=false
    command:
      - "start --auto-build -Dkeycloak.frontendUrl=https://id.steedos.cn -Dkeycloak.forceBackendUrlToFrontendUrl=true"
    volumes:
      # - './steedos-theme.jar:/opt/keycloak/providers/steedos-theme.jar'
      - './build/theme/steedos:/opt/keycloak/themes/steedos'
    depends_on:
      - postgres
    ports:
      - "8080:8080"

volumes:
  postgres_data2:
    driver: local